apiVersion: v1
kind: PersistentVolume
metadata:
  name: os-migrate-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi #Check it!
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  local:
    path: /home/ubuntu/os-migrate #Check it!
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
       - key: kubernetes.io/hostname
          operator: In
          values:
          - argo-single-node #Check it!
